In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import xml.etree.ElementTree as ET
import random
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import mutual_info_score
import pickle
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
import os
import numpy as np
import pandas as pd
import torch


In [ ]:
dataSize=1000
testSize=200
src_count = 20
un_count = 40
src='books'
dest='music'
pivot_num=100
pivot_min_st=10
c_parm=0.1
train=[]
train_target=[]
test=[]
dim=300
target=[]
c=0
i=0
pivotsCounts= []
names = []

In [ ]:
def XML2arrayRAW(neg_path, pos_path):
    reviews = []
    negReviews = []
    posReviews = []

    neg_tree = ET.parse(neg_path)
    neg_root = neg_tree.getroot()
    for rev in neg_root.iter('review'):
        reviews.append(rev.text)
        negReviews.append(rev.text)



    pos_tree = ET.parse(pos_path)
    pos_root = pos_tree.getroot()

    for rev in pos_root.iter('review'):
        reviews.append(rev.text)
        posReviews.append(rev.text)

    return reviews,negReviews,posReviews



In [ ]:
def GetTopNMI(n,CountVectorizer,X,target):
    MI = []
    length = X.shape[1]


    for i in range(length):
        temp=mutual_info_score(X[:, i], target)
        MI.append(temp)
    MIs = sorted(range(len(MI)), key=lambda i: MI[i])[-n:]
    return MIs,MI




In [ ]:
def getCounts(X,i):

    return (sum(X[:,i]))



In [ ]:
def extract_and_split(neg_path, pos_path):
    reviews,n,p = XML2arrayRAW(neg_path, pos_path)
    train, train_target, test, test_target = split_data_balanced(reviews,1000,200)
    train=reviews
    train_target=[]
    test = []
    test_target=[]
    train_target = [0]*1000+[1]*1000
    return train, train_target, test, test_target



In [ ]:
pivotsCounts = []
    #get representation matrix

weight_str = "/content/drive/My Drive/code/AE-PA-SCL/"+ src + "_to_" + dest + "/weights/w_" + src + "_" + dest + "_" + str(pivot_num) + "_" + str(
        pivot_min_st) + "_" + str(dim)+".weights.h5"
    #gets the model weights
#mat= np.load(weight_str)    #gets the encoder as the transformation function
#mat = mat[0]

weights = []
for i in range(4):  # replace `number_of_weights` with the actual number of weights
    w = np.load(f"{weight_str}_weight_{i}.npy")
    weights.append(w)

mat=weights
mat=mat[0]
#model.set_weights(weights)

In [ ]:

pivotsCounts= []
unlabeled = []
names = []

filename ="/content/drive/My Drive/code/AE-PA-SCL/"+src + "_to_" + dest + "/split/"
if not os.path.exists(os.path.dirname(filename)):
    reviews=concatenate_neg_and_pos("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/negative.csv","/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/positive.csv")
    n=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/negative.csv",header=None,encoding='utf-8')
    p=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/positive.csv",header=None,encoding='utf-8')
    test_data_neg = random.sample(range(0, dataSize), testSize)
    test_data_pos = random.sample(range(dataSize, 2*dataSize), testSize)
    random_array = np.concatenate((test_data_neg, test_data_pos))
    train = []
    test = []
    test_target = []
    train_target = []
    for i in range(0, 2*dataSize):
        if i in random_array:
            test.append(reviews[i])
            target = 0 if i < dataSize else 1
            test_target.append(target)
        else:
            train.append(reviews[i])
            target = 0 if i < dataSize else 1
            train_target.append(target)
else:
    with open("/content/drive/My Drive/code/AE-PA-SCL/"+src + "_to_" + dest + "/split/train", 'rb') as f:
        train = pickle.load(f)
    with open("/content/drive/My Drive/code/AE-PA-SCL/"+src + "_to_" + dest + "/split/test", 'rb') as f:
        test = pickle.load(f)
    with open("/content/drive/My Drive/code/AE-PA-SCL/"+src + "_to_" + dest + "/split/train_target", 'rb') as f:
        train_target = pickle.load(f)
    with open("/content/drive/My Drive/code/AE-PA-SCL/"+src + "_to_" + dest + "/split/test_target", 'rb') as f:
        test_target = pickle.load(f)



In [ ]:
train_target

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [ ]:
def concatenate_neg_and_pos(neg,pos):
    data_1 = []
    data_2 = []

# Read the first CSV file
    with open(neg, 'r', newline='', encoding='utf-8') as csvfile1:
        reader = csv.reader(csvfile1)
        for row in reader:
            data_1.append(row)

# Read the second CSV file
    with open(pos, 'r', newline='', encoding='utf-8') as csvfile2:
        reader = csv.reader(csvfile2)
        for row in reader:
            data_2.append(row)

# Combine the data from both files
    reviews = data_1 + data_2
    return reviews

In [ ]:
import csv
import pandas as pd
unlabeled=concatenate_neg_and_pos("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/"+src+"UN.csv",'/content/drive/My Drive/code/AE-PA-SCL/musickan.csv')
source=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/"+src+"UN.csv",header=None,encoding='utf-8') #english labeled data
target=pd.read_csv('/content/drive/My Drive/code/AE-PA-SCL/musickan.csv',header=None,encoding='utf-8') #english labeled data
unlabeled=np.append(source, train,axis=0)
unlabelled=np.append(unlabeled,target,axis=0)

In [ ]:
pip install scikit-learn indic-nlp-library

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 108.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.4/587.4 kB 51.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 127.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 161.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.3/103.3 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.3/119.3 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.5/82.5 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.7/88.7 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 kB 10.0 MB/s eta 0:00:00


In [ ]:
filename = "/content/drive/My Drive/code/AE-PA-SCL/"+src + "_to_" + dest + "/" + "pivotsCounts/" + "pivotsCounts" + src + "_" + dest + "_" + str(
        pivot_num) + "_" + str(pivot_min_st)
with open(filename, 'rb') as f:
    pivotsCounts = pickle.load(f)


In [ ]:
#from langdetect import detect
from sklearn.feature_extraction import DictVectorizer

# Sample tokenized Kannada data
#kannada_tokens = [
   # ["ಈ", "ಒಂದು", "ಕನ್ನಡ", "ಪಠ್ಯವನ್ನು"],
   # ["ಇದು", "ಕನ್ನಡ", "ಪಠ್ಯವನ್ನು", "ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು", "ಪರಿಕ್ಷೆ"],
   ## ["ಕನ್ನಡ", "ಪಠ್ಯವು", "ನಮಗೆ", "ಸಹಾಯ", "ಮಾಡುತ್ತದೆ"]
#]
#target=pd.read_csv('/content/drive/My Drive/my code/musickan.csv',header=None,encoding='utf-8',names=['text'])

import nltk
#natural language tool kit

wn = nltk.WordNetLemmatizer()
#lemmatize is a function inside lemmatizer
#example print(wn.lemmatize('cactus'))
#print(wn.lemmatize('cacti'))
# gives = cactus
def lemmatization(token_txt):
    text = [wn.lemmatize(word) for word in token_txt ]
    return text

import re
import string

punctuation='''!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\n'''
def remove_punctuation(txt):
    txt_nopunct ="".join([c for c in txt if c not in punctuation])
    txt_nopunct = re.sub('\w*\d\w*', '', txt_nopunct)
    return txt_nopunct
unlabelled = pd.Series(unlabelled[:, 0])
unlabel = unlabelled.apply(lambda x: remove_punctuation(x))


from indicnlp.tokenize import indic_tokenize

def tokenize(txt):
    tokens =re.split(' ',txt)
    return tokens

unlabel1 = unlabel.apply(lambda x: tokenize(x.lower()))


#tokens=kan_data['kan_tweets_tokens']
def clean(txt):
    for i in txt:
        if len(i)==1:
            del(i)
    return txt
unlabel2 = unlabel1.apply(lambda x: clean(x))
#print(target['text3'])
#print(unlabel2.head())
# Convert tokenized data to a list of dictionaries
token_count = []
for tokens in unlabel2:
    #print(tokens)
    token_count_dict1 = {}
    for token in tokens:
        #print(token_count_dict)
        if token in token_count_dict1:
            token_count_dict1[token] += 1
        else:
            token_count_dict1[token] = 1
    token_count.append(token_count_dict1)


# Create an instance of DictVectorizer
bigram_vectorizer_unlabeled = DictVectorizer(sparse=False)

# Fit and transform the token counts
X_2_train_unlabeled = bigram_vectorizer_unlabeled.fit_transform(token_count)

# Convert to an array for inspection
#X_array = X.toarray()

# Get feature names (vocabulary)
feature_names_unlabel = bigram_vectorizer_unlabeled.get_feature_names_out()
for i in range(0,len(feature_names_unlabel)):
    print(feature_names_unlabel[i])
# Print the feature names and the array
  #print("Feature Names:", feature_names)
print("Feature Array:\n", X_2_train_unlabeled)


<>:30: SyntaxWarning: invalid escape sequence '\w'
<>:30: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-2235245568.py:30: SyntaxWarning: invalid escape sequence '\w'
  txt_nopunct = re.sub('\w*\d\w*', '', txt_nopunct)



	
		
			houses
			lo
			the
		calcio
		calling
		expressions
		il
		italian
		la
		made
		meals
		professional
		the
		time
		waiting
	a
	after
	against
	all
	america
	american
	an
	and
	april
	are
	as
	at
	attention
	attracting
	authentic
	bad
	basic
	businesses
	celebrations
	china
	compliments
	conservatives
	creativity
	dating
	demonstrated
	did
	does
	driving
	earlier
	eye
	family
	fighting
	for
	form
	hal
	have
	how
	i
	il
	im
	in
	innovation
	is
	italy
	its
	la
	large
	le
	lies
	ma
	management
	mermaids
	metrics
	millhone
	monetary
	more
	navigating
	nestorian
	networks
	number
	on
	one
	pat
	peoples
	physical
	pig
	pro
	ravitch
	sadly
	seek
	should
	simple
	so
	speaking
	strong
	the
	then
	there
	this
	though
	tinkerbell
	today
	tu
	v
	was
	ways
	we
	what
	whats
	when
	where
	while
	who
	why
	will
a
aa
aaaaa
aafto
aahed
aaii
aaiicoms
aaiis
aand
aarp
aarrgggh
ab
aba
abaci
aback
abackthis
abagnale
abagnales
abandon
abandoned
abandoning
abandonment
abandonmentkozols
abandonmentsh

In [ ]:
len(pivotsCounts)

1346

In [ ]:
print(train)

[["Horrible book, horrible.\n\tTHis book was horrible.  If it was possible to rate it lower than one star i would have.  I am an avid reader and picked this book up after my mom had gotten it from a friend.  I read half of it, suffering from a headache the entire time, and then got to the part about the relationship the 13 year old boy had with a 33 year old man and i lit this book on fire.  One less copy in the world...don't waste your money.\n\nI wish i had the time spent reading this book back so i could use it for better purposes.  THis book wasted my life"], ['shallow self-indulgence\n\tI like to use the Amazon reviews when purchasing books, especially alert for dissenting perceptions about higly rated items, which usually disuades me from a selection.  So I offer this review that seriously questions the popularity of this work - I found it smug, self-serving and self-indulgent, written by a person with little or no empathy, especially for the people he castigates. For example, hi

In [ ]:
trainSent = train
trainsen = [' '.join(sublist) for sublist in trainSent] # Convert list of lists to list of strings
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2), token_pattern=r'\b\w+\b', min_df=20, binary=True)
X_2_train = bigram_vectorizer.fit_transform(trainsen).toarray() # Pass list of strings to fit_transform

# Assuming bigram_vectorizer_unlabeled expects a list of dictionaries
# Create dictionary for test data
trainSent_dict = [{word: 1 for word in sentence} for sentence in trainsen]
X_2_test_unlabeld = bigram_vectorizer_unlabeled.transform(trainSent_dict) # changed trainSent to trainSent_dict

#delete the pivots from the test matrix
XforREP = np.delete(X_2_test_unlabeld, pivotsCounts, 1)  # delete second column of C

rep = XforREP.dot(mat)

In [ ]:
print((pivotsCounts))

[5714, 53310, 16585, 48099, 13209, 32726, 33036, 13935, 3730, 20730, 53280, 54390, 24760, 51615, 14693, 36996, 53454, 13197, 23424, 33078, 40278, 22396, 54677, 14452, 31212, 4211, 36985, 50014, 4685, 47147, 23557, 50857, 18082, 28623, 12902, 18288, 4224, 28613, 4625, 20103, 54817, 20494, 6593, 41745, 45653, 47676, 53822, 2285, 31664, 54701, 54663, 41037, 4760, 2459, 49089, 45332, 46537, 12774, 15679, 13222, 15798, 20481, 49010, 34145, 44460, 46370, 44700, 23873, 43427, 24943, 24688, 29952, 34888, 53528, 11504, 680, 50221, 38521, 22073, 21260, 55341, 34816, 29641, 343, 23238, 7051, 42360, 4038, 27914, 42472, 17455, 9480, 37369, 4435, 40795, 30083, 29209, 18070, 10320, 40285, 55665, 57359, 59292, 68944, 55735, 61933, 61938, 62441, 66357, 65091, 69916, 57517, 66380, 58989, 56734, 57830, 57407, 67231, 59484, 56284, 55685, 56406, 71332, 57531, 69460, 60597, 66980, 70653, 58204, 70905, 64417, 58081, 65247, 45115, 49792, 25379, 14296, 49799, 48493, 14294, 5706, 32508, 42187, 20277, 43157, 397

In [ ]:
print(X_2_test_unlabeld.shape)

(1600, 71815)


In [ ]:
print(type(bigram_vectorizer_unlabeled))

<class 'sklearn.feature_extraction._dict_vectorizer.DictVectorizer'>


In [ ]:
Test = [' '.join(sublist) for sublist in test]
X_dev_test = bigram_vectorizer.transform(Test).toarray()
test_dict = [{word: 1 for word in sentence} for sentence in test]
X_dev_test_unlabeled = bigram_vectorizer_unlabeled.transform(test_dict)
#X_dev_test_unlabeled = bigram_vectorizer_unlabeled.transform(test).toarray()
XforREP_dev = np.delete(X_dev_test_unlabeled, pivotsCounts, 1)  # delete second column of C
XforREP_dev = XforREP_dev.dot(mat)
devAllFeatures = np.concatenate((X_dev_test,XforREP_dev),1)

allfeatures = np.concatenate((X_2_train, rep), axis=1)


In [ ]:
lbl_num = 1000
dest_test=concatenate_neg_and_pos("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/negative.csv","/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/positive.csv")
source=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/negative.csv",header=None,encoding='utf-8')
target=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL/English/"+src+"/positive.csv",header=None,encoding='utf-8')
#dest_test, source, target = XML2arrayRAW("./data/"+dest+"/negative.parsed","./data/"+dest+"/positive.parsed")
dest_test_target= [0]*lbl_num+[1]*lbl_num

dest_Test = [' '.join(sublist) for sublist in dest_test]
X_dest = bigram_vectorizer.transform(dest_Test).toarray()
dest_dict = [{word: 1 for word in sentence} for sentence in dest_test]
X_2_test = bigram_vectorizer_unlabeled.transform(dest_dict)
XforREP_dest = np.delete(X_2_test, pivotsCounts, 1)  # delete second column of C
rep_for_dest = XforREP_dest.dot(mat)
allfeaturesFinal = np.concatenate((X_dest, rep_for_dest), axis=1)



In [ ]:
print(len([1]*lbl_num))

1000


In [ ]:
print(X_dest.shape)

(2000, 2259)


In [ ]:

logreg = LogisticRegression(C=c_parm)
logreg.fit(X_2_train, train_target)
lgs = logreg.score(X_dest, dest_test_target)
log_dev_source = logreg.score(X_dev_test, test_target)



In [ ]:
print(f"Number of samples in X: {X_2_train}")
print(f"Number of samples in y: {train_target}")

Number of samples in X: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Number of samples in y: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

seeds = [42, 7, 21, 13, 99]
results_metrics = []

for seed in seeds:
    np.random.seed(seed)
    random.seed(seed)



    logreg =  LogisticRegression(C=c_parm)

    logreg.fit(allfeatures, train_target)

    lg = logreg.score(allfeaturesFinal, dest_test_target)
    log_dev_all = logreg.score(devAllFeatures,test_target)
    y_pred = logreg.predict(allfeaturesFinal)

    precision = precision_score(dest_test_target, y_pred, average='binary')
    recall = recall_score(dest_test_target, y_pred, average='binary')
    f1 = f1_score(dest_test_target, y_pred, average='binary')

    results_metrics.append((precision, recall, f1))
    print(f"Seed {seed}: Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
    #with open(filename, "a") as myfile:
    #myfile.write(f"Seed {seed}: pivot num={pivot_num}, min freq={pivot_min_st}, dim={dim}, result={lg_score}, c_parm={c_parm}\n")




Seed 42: Precision=0.9006, Recall=0.9700, F1=0.9340
Seed 7: Precision=0.9006, Recall=0.9700, F1=0.9340
Seed 21: Precision=0.9006, Recall=0.9700, F1=0.9340
Seed 13: Precision=0.9006, Recall=0.9700, F1=0.9340
Seed 99: Precision=0.9006, Recall=0.9700, F1=0.9340


In [ ]:
#from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

# Step 1: Fit the model
#logreg = LogisticRegression(C=c_parm)
#logreg.fit(allfeatures, train_target)

# Step 2: Make predictions on the test data
#y_pred = logreg.predict(allfeaturesFinal)

# Step 3: Calculate precision, recall, and F1 score
#precision = precision_score(dest_test_target, y_pred, average='binary')  # Use 'binary' or 'macro' or 'weighted' based on your problem
#recall = recall_score(dest_test_target, y_pred, average='binary')      # Adjust average method as needed
#f1 = f1_score(dest_test_target, y_pred, average='binary')               # Adjust average method as needed

# Print metrics
#print(f'Precision: {precision}')
#print(f'Recall: {recall}')
#print(f'F1 Score: {f1}')

In [ ]:


    logregR =  LogisticRegression(C=c_parm)

    logregR.fit(rep, train_target)
    log_dev_rep = logregR.score(XforREP_dev,test_target)
    lgR = logregR.score(rep_for_dest, dest_test_target)

In [ ]:
filename = "/content/drive/My Drive/code/AE-PA-SCL/"+src+"_to_"+dest+"/"+"results1/"+src+"_to_"+dest
if not os.path.exists(os.path.dirname(filename)):
        os.makedirs(os.path.dirname(filename))

sentence = "pivot num = " + str(pivot_num) + " , min freq = " + str(pivot_min_st) + " dim = " + str(
        dim) + " result = " + str(lg) + " c_parm = " + str(c_parm)
print(sentence)

with open(filename, "a") as myfile:
    myfile.write(sentence+"\n")
