In [ ]:
dataSize=1000
testSize=200
src_count = 20
un_count = 40
src='books'
dest='music'
pivot_num=200
pivot_min_st=10
c_parm=0.1
train=[]
train_target=[]
test=[]
dim=300
target=[]
c=0
i=0
pivotsCounts= []
names = []

In [ ]:
import xml.etree.ElementTree as ET
import random
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import mutual_info_score
import pickle
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
import os


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
def XML2arrayRAW(neg_path, pos_path):
    reviews = []
    negReviews = []
    posReviews = []

    neg_tree = ET.parse(neg_path)
    neg_root = neg_tree.getroot()
    for rev in neg_root.iter('review'):
        reviews.append(rev.text)
        negReviews.append(rev.text)



    pos_tree = ET.parse(pos_path)
    pos_root = pos_tree.getroot()

    for rev in pos_root.iter('review'):
        reviews.append(rev.text)
        posReviews.append(rev.text)

    return reviews,negReviews,posReviews



In [ ]:
def GetTopNMI(n,CountVectorizer,X,target):
    MI = []
    length = X.shape[1]


    for i in range(length):
        temp=mutual_info_score(X[:, i], target)
        MI.append(temp)
    MIs = sorted(range(len(MI)), key=lambda i: MI[i])[-n:]
    return MIs,MI




In [ ]:
def getCounts(X,i):

    return (sum(X[:,i]))



In [ ]:
def extract_and_split(neg_path, pos_path):
    reviews,n,p = XML2arrayRAW(neg_path, pos_path)
    train, train_target, test, test_target = split_data_balanced(reviews,1000,200)
    train=reviews
    train_target=[]
    test = []
    test_target=[]
    train_target = [0]*1000+[1]*1000
    return train, train_target, test, test_target



In [ ]:
pivotsCounts = []
    #get representation matrix

weight_str = "/content/drive/My Drive/code/AE-PA-SCL-FT/"+ src + "_to_" + dest + "/weights/w_" + src + "_" + dest + "_" + str(pivot_num) + "_" + str(
        pivot_min_st) + "_" + str(dim)+".weights.h5"
    #gets the model weights
#mat= np.load(weight_str)    #gets the encoder as the transformation function
#mat = mat[0]

weights = []
for i in range(4):  # replace `number_of_weights` with the actual number of weights
    w = np.load(f"{weight_str}_weight_{i}.npy")
    weights.append(w)

mat=weights
mat=mat[0]
#model.set_weights(weights)

In [ ]:
weight_str

'/content/drive/My Drive/code/AE-PA-SCL-FT/books_to_music/weights/w_books_music_200_10_300.weights.h5'

In [ ]:

pivotsCounts= []
unlabeled = []
names = []

filename ="/content/drive/My Drive/code/AE-PA-SCL-FT/"+src + "_to_" + dest + "/split/"
if not os.path.exists(os.path.dirname(filename)):
    reviews=concatenate_neg_and_pos("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/negative.csv","/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/positive.csv")
    n=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/negative.csv",header=None,encoding='utf-8')
    p=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/positive.csv",header=None,encoding='utf-8')
    test_data_neg = random.sample(range(0, dataSize), testSize)
    test_data_pos = random.sample(range(dataSize, 2*dataSize), testSize)
    random_array = np.concatenate((test_data_neg, test_data_pos))
    train = []
    test = []
    test_target = []
    train_target = []
    for i in range(0, 2*dataSize):
        if i in random_array:
            test.append(reviews[i])
            target = 0 if i < dataSize else 1
            test_target.append(target)
        else:
            train.append(reviews[i])
            target = 0 if i < dataSize else 1
            train_target.append(target)
else:
    with open("/content/drive/My Drive/code/AE-PA-SCL-FT/"+src + "_to_" + dest + "/split/train", 'rb') as f:
        train = pickle.load(f)
    with open("/content/drive/My Drive/code/AE-PA-SCL-FT/"+src + "_to_" + dest + "/split/test", 'rb') as f:
        test = pickle.load(f)
    with open("/content/drive/My Drive/code/AE-PA-SCL-FT/"+src + "_to_" + dest + "/split/train_target", 'rb') as f:
        train_target = pickle.load(f)
    with open("/content/drive/My Drive/code/AE-PA-SCL-FT/"+src + "_to_" + dest + "/split/test_target", 'rb') as f:
        test_target = pickle.load(f)



In [ ]:
train_target

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [ ]:
def concatenate_neg_and_pos(neg,pos):
    data_1 = []
    data_2 = []

# Read the first CSV file
    with open(neg, 'r', newline='', encoding='utf-8') as csvfile1:
        reader = csv.reader(csvfile1)
        for row in reader:
            data_1.append(row)

# Read the second CSV file
    with open(pos, 'r', newline='', encoding='utf-8') as csvfile2:
        reader = csv.reader(csvfile2)
        for row in reader:
            data_2.append(row)

# Combine the data from both files
    reviews = data_1 + data_2
    return reviews

In [ ]:
import csv
import pandas as pd
unlabeled=concatenate_neg_and_pos("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/"+src+"UN.csv",'/content/drive/My Drive/code/AE-PA-SCL-FT/musickan.csv')
source=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/"+src+"UN.csv",header=None,encoding='utf-8') #english labeled data
target=pd.read_csv('/content/drive/My Drive/code/AE-PA-SCL-FT/musickan.csv',header=None,encoding='utf-8') #english labeled data
unlabeled=np.append(source, train,axis=0)
unlabelled=np.append(unlabeled,target,axis=0)

In [ ]:
pip install scikit-learn indic-nlp-library

In [ ]:
filename = "/content/drive/My Drive/code/AE-PA-SCL-FT/"+src + "_to_" + dest + "/" + "pivotsCounts/" + "pivotsCounts" + src + "_" + dest + "_" + str(
        pivot_num) + "_" + str(pivot_min_st)
with open(filename, 'rb') as f:
    pivotsCounts = pickle.load(f)


In [ ]:
#from langdetect import detect
from sklearn.feature_extraction import DictVectorizer

# Sample tokenized Kannada data
#kannada_tokens = [
   # ["ಈ", "ಒಂದು", "ಕನ್ನಡ", "ಪಠ್ಯವನ್ನು"],
   # ["ಇದು", "ಕನ್ನಡ", "ಪಠ್ಯವನ್ನು", "ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು", "ಪರಿಕ್ಷೆ"],
   ## ["ಕನ್ನಡ", "ಪಠ್ಯವು", "ನಮಗೆ", "ಸಹಾಯ", "ಮಾಡುತ್ತದೆ"]
#]
#target=pd.read_csv('/content/drive/My Drive/my code/musickan.csv',header=None,encoding='utf-8',names=['text'])

import nltk
#natural language tool kit

wn = nltk.WordNetLemmatizer()
#lemmatize is a function inside lemmatizer
#example print(wn.lemmatize('cactus'))
#print(wn.lemmatize('cacti'))
# gives = cactus
def lemmatization(token_txt):
    text = [wn.lemmatize(word) for word in token_txt ]
    return text

import re
import string

punctuation='''!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\n'''
def remove_punctuation(txt):
    txt_nopunct ="".join([c for c in txt if c not in punctuation])
    txt_nopunct = re.sub('\w*\d\w*', '', txt_nopunct)
    return txt_nopunct
unlabelled = pd.Series(unlabelled[:, 0])
unlabel = unlabelled.apply(lambda x: remove_punctuation(x))


from indicnlp.tokenize import indic_tokenize

def tokenize(txt):
    tokens =re.split(' ',txt)
    return tokens

unlabel1 = unlabel.apply(lambda x: tokenize(x.lower()))


#tokens=kan_data['kan_tweets_tokens']
def clean(txt):
    for i in txt:
        if len(i)==1:
            del(i)
    return txt
unlabel2 = unlabel1.apply(lambda x: clean(x))
#print(target['text3'])
#print(unlabel2.head())
# Convert tokenized data to a list of dictionaries
token_count = []
for tokens in unlabel2:
    #print(tokens)
    token_count_dict1 = {}
    for token in tokens:
        #print(token_count_dict)
        if token in token_count_dict1:
            token_count_dict1[token] += 1
        else:
            token_count_dict1[token] = 1
    token_count.append(token_count_dict1)


# Create an instance of DictVectorizer
bigram_vectorizer_unlabeled = DictVectorizer(sparse=False)

# Fit and transform the token counts
X_2_train_unlabeled = bigram_vectorizer_unlabeled.fit_transform(token_count)

# Convert to an array for inspection
#X_array = X.toarray()

# Get feature names (vocabulary)
feature_names_unlabel = bigram_vectorizer_unlabeled.get_feature_names_out()
for i in range(0,len(feature_names_unlabel)):
    print(feature_names_unlabel[i])
# Print the feature names and the array
  #print("Feature Names:", feature_names)
print("Feature Array:\n", X_2_train_unlabeled)


Streaming output truncated to the last 5000 lines.
ಮುಸುಕು
ಮೂಕ
ಮೂಕರನ್ನಾಗಿ
ಮೂಕರನ್ನಾಗಿಸಿದೆ
ಮೂಕವಿಸ್ಮಿತರಾಗುವುದಿಲ್ಲ
ಮೂಗಿನ
ಮೂಗೇಟುಗಳನ್ನು
ಮೂಡತೊಡಗಿತು
ಮೂಡಿ
ಮೂಡಿತು
ಮೂಡಿಬಂದಿವೆ
ಮೂಡಿಯಾಗಿ
ಮೂಡಿಸಲು
ಮೂಡಿಸುತ್ತದೆ
ಮೂಡ್
ಮೂಡ್‌ಗಳನ್ನು
ಮೂಡ್‌ಗೆ
ಮೂಡ್‌ನಲ್ಲಿದ್ದರೆ
ಮೂಡ್‌ನಲ್ಲಿದ್ದೇನೆ
ಮೂನ್‌ನಲ್ಲಿ
ಮೂರನೆಯ
ಮೂರನೆಯದನ್ನು
ಮೂರನೆಯದು
ಮೂರನೇ
ಮೂರರಲ್ಲಿ
ಮೂರು
ಮೂರುಟ್ರ್ಯಾಕ್
ಮೂರುಮಾರ್ಗದ
ಮೂರುವಿಭಾಗದ
ಮೂರೂವರೆ
ಮೂರ್ಖ
ಮೂರ್ಖತನ
ಮೂರ್ಖತನದ
ಮೂರ್ಖತನದಿಂದ
ಮೂರ್ಖರಂತೆ
ಮೂರ್ಖರನ್ನಾಗಿಸುತ್ತದೆ
ಮೂರ್ಖರಾಗಿರಿ
ಮೂರ್ಖರೆಂದು
ಮೂರ್ಛೆ
ಮೂರ್ಛೆಗೊಳಿಸಲು
ಮೂಲ
ಮೂಲಕ
ಮೂಲಕವೂ
ಮೂಲಕ್ಕಿಂತ
ಮೂಲಕ್ಕೆ
ಮೂಲಗಳಿಂದ
ಮೂಲತಃ
ಮೂಲದಂತೆ
ಮೂಲದಲ್ಲಿ
ಮೂಲಭೂತ
ಮೂಲಭೂತವಾಗಿ
ಮೂಲಭೂತವಾಗಿದೆ
ಮೂಲವನ್ನು
ಮೂಲವಲ್ಲದ
ಮೂಲವಾಗಿದೆ
ಮೂಲವು
ಮೂಲವೂ
ಮೂಲೆ
ಮೂಲೆಯ
ಮೂಲೆಯಲ್ಲಿ
ಮೂಳೆ
ಮೂಳೆಗಳನ್ನು
ಮೂಳೆಗಳು
ಮೂಳೆಯವರೆಗೆ
ಮೂವತ್ತು
ಮೂವರ
ಮೂವರೊಂದಿಗೆ
ಮೂವಿಗಳನ್ನು
ಮೂವ್
ಮೃಗೀಯವಾಗಿದೆ
ಮೃದು
ಮೃದುಗೊಳಿಸಲಾಗುತ್ತದೆ
ಮೃದುತ್ವ
ಮೃದುತ್ವವು
ಮೃದುವಾಗಿ
ಮೃದುವಾದ
ಮೆ
ಮೆಕ್ಕಾರ್ಟ್ನಿಎಸ್ಕ್ಯೂ
ಮೆಕ್ಯಾನಿಕಲ್
ಮೆಗಾಲೊಮೇನಿಯಾಕ್
ಮೆಚ್ಚಬೇಕು
ಮೆಚ್ಚಿದ
ಮೆಚ್ಚಿದರೂ
ಮೆಚ್ಚಿದೆ
ಮೆಚ್ಚಿನ
ಮೆಚ್ಚಿನವನ್ನು
ಮೆಚ್ಚಿನವಲ್ಲದಿದ್ದರೂ
ಮೆಚ್ಚಿನವು
ಮೆಚ್ಚಿನವುಗಳ
ಮೆಚ್ಚಿನವುಗಳಲ್ಲ
ಮೆಚ್ಚಿನವುಗಳಲ್ಲದಿದ್ದರೂ
ಮೆಚ್ಚಿನವುಗಳಲ್ಲಿ
ಮೆಚ್ಚಿನವುಗಳವರೆಗೆ
ಮೆಚ್ಚಿನವುಗಳಾಗಿ
ಮ

In [ ]:

trainSent=train
trainsen = [' '.join(sublist) for sublist in trainSent]
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2), token_pattern=r'\b\w+\b', min_df=20, binary=True)
X_2_train = bigram_vectorizer.fit_transform(trainsen).toarray()


trainSent_dict = [{word: 1 for word in sentence} for sentence in trainSent]
X_2_test_unlabeld = bigram_vectorizer_unlabeled.transform(trainSent_dict)
    #delete the pivots from the test matrix
XforREP = np.delete(X_2_test_unlabeld, pivotsCounts, 1)  # delete second column of C

rep = XforREP.dot(mat)


In [ ]:
print(type(bigram_vectorizer_unlabeled))

<class 'sklearn.feature_extraction._dict_vectorizer.DictVectorizer'>


In [ ]:
Test = [' '.join(sublist) for sublist in test]
X_dev_test = bigram_vectorizer.transform(Test).toarray()
test_dict = [{word: 1 for word in sentence} for sentence in test]
X_dev_test_unlabeled = bigram_vectorizer_unlabeled.transform(test_dict)
#X_dev_test_unlabeled = bigram_vectorizer_unlabeled.transform(test).toarray()
XforREP_dev = np.delete(X_dev_test_unlabeled, pivotsCounts, 1)  # delete second column of C
XforREP_dev = XforREP_dev.dot(mat)
devAllFeatures = np.concatenate((X_dev_test,XforREP_dev),1)

allfeatures = np.concatenate((X_2_train, rep), axis=1)


In [ ]:
lbl_num = 1000
dest_test=concatenate_neg_and_pos("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/negative.csv","/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/positive.csv")
source=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/negative.csv",header=None,encoding='utf-8')
target=pd.read_csv("/content/drive/My Drive/code/AE-PA-SCL-FT/English/"+src+"/positive.csv",header=None,encoding='utf-8')
#dest_test, source, target = XML2arrayRAW("./data/"+dest+"/negative.parsed","./data/"+dest+"/positive.parsed")
dest_test_target= [0]*lbl_num+[1]*lbl_num

dest_Test = [' '.join(sublist) for sublist in dest_test]
X_dest = bigram_vectorizer.transform(dest_Test).toarray()
dest_dict = [{word: 1 for word in sentence} for sentence in dest_test]
X_2_test = bigram_vectorizer_unlabeled.transform(dest_dict)
XforREP_dest = np.delete(X_2_test, pivotsCounts, 1)  # delete second column of C
rep_for_dest = XforREP_dest.dot(mat)
allfeaturesFinal = np.concatenate((X_dest, rep_for_dest), axis=1)



In [ ]:
print(len([1]*lbl_num))

1000


In [ ]:
print(X_dest.shape)

(2000, 2290)


In [ ]:

logreg = LogisticRegression(C=c_parm)
logreg.fit(X_2_train, train_target)
lgs = logreg.score(X_dest, dest_test_target)
log_dev_source = logreg.score(X_dev_test, test_target)



In [ ]:
print(f"Number of samples in X: {X_2_train}")
print(f"Number of samples in y: {train_target}")

Number of samples in X: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Number of samples in y: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
logreg =  LogisticRegression(C=c_parm)

logreg.fit(allfeatures, train_target)

lg = logreg.score(allfeaturesFinal, dest_test_target)
log_dev_all = logreg.score(devAllFeatures,test_target)




In [ ]:
#from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

# Step 1: Fit the model
#logreg = LogisticRegression(C=c_parm)
#logreg.fit(allfeatures, train_target)

# Step 2: Make predictions on the test data
y_pred = logreg.predict(allfeaturesFinal)

# Step 3: Calculate precision, recall, and F1 score
precision = precision_score(dest_test_target, y_pred, average='binary')  # Use 'binary' or 'macro' or 'weighted' based on your problem
recall = recall_score(dest_test_target, y_pred, average='binary')      # Adjust average method as needed
f1 = f1_score(dest_test_target, y_pred, average='binary')               # Adjust average method as needed

# Print metrics
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')

Precision: 0.9418837675350702
Recall: 0.94
F1 Score: 0.9409409409409409


In [ ]:
logregR =  LogisticRegression(C=c_parm)

logregR.fit(rep, train_target)
log_dev_rep = logregR.score(XforREP_dev,test_target)
lgR = logregR.score(rep_for_dest, dest_test_target)

In [ ]:
filename = "/content/drive/My Drive/code/AE-PA-SCL-FT/"+src+"_to_"+dest+"/"+"results1/"+src+"_to_"+dest
if not os.path.exists(os.path.dirname(filename)):
        os.makedirs(os.path.dirname(filename))

sentence = "pivot num = " + str(pivot_num) + " , min freq = " + str(pivot_min_st) + " dim = " + str(
        dim) + " result = " + str(lg) + " c_parm = " + str(c_parm)
print(sentence)

with open(filename, "a") as myfile:
    myfile.write(sentence+"\n")


pivot num = 200 , min freq = 10 dim = 300 result = 0.941 c_parm = 0.1
